### ISSUE TITLE
Not accepted for Hacktoberfest 2022

### ISSUE THREAD

**Issue by umadhatri** [TARANG0503/DSA-Practice#185]
It says that the repo is not accpeted for Hacktoberfest 2022. Please let me know if it is the repo or my PR. Thanks and cheers!
<img width="907" alt="Screen Shot 2022-10-01 at 2 32 52 PM" src="https://user-images.githubusercontent.com/97341880/193401978-0cd1acc3-d1a9-47c2-9f09-4448969765fd.png">

**Comment by TARANG0503** [comment]
It simply means that your PR has not been accepted by maintainer till that time. If a repo is not participating, it shows "NOT-PARTICIPATING".

**Comment by umadhatri** [comment]
Oh, thank you for that!
