### ISSUE TITLE
Add DSA Questions

### ISSUE THREAD

**Issue by PriyanshuGarg26** [TARANG0503/DSA-Practice#196]
Want to add some DSA questions like 2Sum, 3Sum, Kadane's algo, reverse linked list, next greater element, odd-even linked list

**Comment by strngpowty** [comment]
I would like to contribute on this issue. Can you add hacktoberfest / hacktoberfest-accepted tag to be issue.

**Comment by TARANG0503** [comment]
There are already many websites for questions. It will be very difficult for us to check plagiarism in PRs. Therefore we don't accept only question PRs. 

You can add question at the top of your solution as comments.

**Comment by preerna** [comment]
please assign this to me

**Comment by muskaanrajput14** [comment]
Please assign it to me

**Comment by PriyanshuGarg26** [comment]
> There are already many websites for questions. It will be very difficult for us to check plagiarism in PRs. Therefore we don't accept only question PRs.
> 
> You can add question at the top of your solution as comments.

Ok,  Sure . Pls assign this issue to me.

**Comment by TARANG0503** [comment]
You all can add any question with a solution. Just create a pull request and we will merge it after reviewing.
