### ISSUE TITLE
Selection sort in C++

### ISSUE THREAD

**Issue by AdityaMore7000** [TARANG0503/DSA-Practice#244]
Hello @TARANG0503, I would like to add C++ code for selection sort. I will write easily readable code with comments that explain problem statement as well as the code.

Kindly add the hacktoberfest-accepted labels to my pull request

Please assign me this task and give me an opportunity to contribute to our community through your project. Looking forward to get a response from you. Thank you

**Comment by TARANG0503** [comment]
You all can add any question with a solution. Just create a pull request and we will merge it after reviewing.
