### ISSUE TITLE
Cpp implemetation of Trie Data Structure with all basic functionalities

### ISSUE THREAD

**Issue by Rahul-Roy-21** [TARANG0503/DSA-Practice#332]
Hi @TARANG0503 , please assign me to this issue with an added tag 'hacktoberfest-accepted'

**Comment by sandesh-3112** [comment]
please assign this task to me under hacktoberfest tag

**Comment by TARANG0503** [comment]
Create a pull request for that.

**Comment by Rahul-Roy-21** [comment]
@TARANG0503,  please merge my PR #368 and add hacktoberfest-accepted tag
