### ISSUE TITLE
Connect N ropes with minimum cost using Priority Queue

### ISSUE THREAD

**Issue by Spardha-hash** [TARANG0503/DSA-Practice#396]
@TARANG0503 Please assign this issue to me. Can I directly raise the PR next time without creating the issue??

**Comment by Sandyy07** [comment]
Kindly Please assign me this issue.

**Comment by Unable1203** [comment]
I want to work on this

**Comment by TARANG0503** [comment]
Please create a pull request for any question you want to contribute. There can be more than one solution for any question. So you all can contribute your solutions.
