### ISSUE TITLE
Rotten Oranges Problem using BFS (Graph)

### ISSUE THREAD

**Issue by aakashraj01** [TARANG0503/DSA-Practice#406]
Hey, @TARANG0503 , I am willing to add this question in C++ . Can you please assign me this issue under Hacktoberfest2022 label :)  ?

**Comment by Sandyy07** [comment]
Kindly Please assign me this issue.

**Comment by devanshikapla** [comment]
Kindly Assign me this issue.

**Comment by Unable1203** [comment]
I want to work onthis

**Comment by TARANG0503** [comment]
Please create a pull request for any question you want to contribute. There can be more than one solution for any question. So you all can contribute your solutions.
