### ISSUE TITLE
Peak index in a mountain array in cpp

### ISSUE THREAD

**Issue by Rahul-Jain-1** [TARANG0503/DSA-Practice#417]
hello @TARANG0503  I would like to implement code of  **Peak index in a mountain array** in cpp  (medium level problem in leetcode). pls assign me this under **Hacktoberfest** accepted label.

**Comment by himanshu30-max** [comment]
hello @TARANG0503 i have implemented the code for the above problem and created a pull request please review it

**Comment by TARANG0503** [comment]
Merged.
