### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by aish0749** [TARANG0503/DSA-Practice#463]
I would like to add Sieve of Eratosthenes algorithm as a contribution for the Hacktober Fest 2022, could you assign this issue to me.

**Comment by TARANG0503** [comment]
Ok. Create a PR for that.

**Comment by aish0749** [comment]
ok, thanks for replying.

**Comment by aish0749** [comment]
can you put this under the tag of hacktoberfest 2022
