### ISSUE TITLE
0-1 Knapsack algorithm

### ISSUE THREAD

**Issue by aish0749** [TARANG0503/DSA-Practice#481]
I would like to implement the 0-1 knapsack algorithm (DP).
could you assign it to me ?

**Comment by TARANG0503** [comment]
Ok. Create a PR for that.

**Comment by aish0749** [comment]
actually my pr got excluded from hacktoberfest? could you tell me the reason

**Comment by Divyanshmishra101010** [comment]
I would like to implement the 0-1 knapsack algorithm for you...can you please assign it to me?
